# Generated by Django 4.2.5 on 2023-09-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='escaperoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escaperoom_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
